import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1791226223363 implements MigrationInterface {
    name = 'InitialSchema1791226223363'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."user_role" AS ENUM('USER', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "users" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT gen_random_uuid(), "email" citext NOT NULL, "password_hash" text, "role" "public"."user_role" NOT NULL DEFAULT 'USER', "display_name" character varying(120), "locale" character varying(10) NOT NULL DEFAULT 'en', "stripe_customer_id" character varying(64), "email_verified_at" TIMESTAMP WITH TIME ZONE, "last_login_at" TIMESTAMP WITH TIME ZONE, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_5ffbe395603641c29e8ce9b4c97" UNIQUE ("stripe_customer_id"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."media_kind" AS ENUM('AUDIO', 'IMAGE')`);
        await queryRunner.query(`CREATE TYPE "public"."media_status" AS ENUM('PENDING', 'READY', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "media_assets" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT gen_random_uuid(), "kind" "public"."media_kind" NOT NULL, "bucket" character varying(255) NOT NULL, "s3_key" character varying(1024) NOT NULL, "mime_type" character varying(127) NOT NULL, "size_bytes" bigint NOT NULL, "duration_ms" integer, "status" "public"."media_status" NOT NULL DEFAULT 'PENDING', "uploaded_by_id" uuid NOT NULL, CONSTRAINT "UQ_07afd35cc72315e6ec00f36b659" UNIQUE ("bucket", "s3_key"), CONSTRAINT "PK_ca47e9f67a5e5d8af1e75d66ee6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "issues" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "slug" character varying(80) NOT NULL, "name" character varying(120) NOT NULL, CONSTRAINT "UQ_5df7524d403b3374b9c65339ea4" UNIQUE ("slug"), CONSTRAINT "PK_9d8ecbbeff46229c700f0449257" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "track_issues" ("track_id" uuid NOT NULL, "issue_id" uuid NOT NULL, CONSTRAINT "PK_07a759ebe5eb92b280c561ff0dd" PRIMARY KEY ("track_id", "issue_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cf45166462d38ec72a4adea48f" ON "track_issues"  ("issue_id") `);
        await queryRunner.query(`CREATE TYPE "public"."wu_xing_element" AS ENUM('WOOD', 'FIRE', 'EARTH', 'METAL', 'WATER')`);
        await queryRunner.query(`CREATE TABLE "elements" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "code" "public"."wu_xing_element" NOT NULL, "name" character varying(50) NOT NULL, CONSTRAINT "UQ_0fda387d90e59218bae431859b0" UNIQUE ("code"), CONSTRAINT "PK_8ddc95518584d13bd838fe99a77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."polarity" AS ENUM('YIN', 'YANG')`);
        await queryRunner.query(`CREATE TABLE "meridians" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "element_id" uuid, "code" character varying(4) NOT NULL, "name" character varying(100) NOT NULL, "polarity" "public"."polarity" NOT NULL, CONSTRAINT "UQ_89210da2a07c1785a8b305bc21c" UNIQUE ("code"), CONSTRAINT "PK_6ca69c1c7900f954b3c231001eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3148131d1ea8728e33b67cbcb3" ON "meridians"  ("element_id") `);
        await queryRunner.query(`CREATE TABLE "track_meridians" ("track_id" uuid NOT NULL, "meridian_id" uuid NOT NULL, CONSTRAINT "PK_f42d5eb48346d1559d246777b64" PRIMARY KEY ("track_id", "meridian_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_48c337ae000ee39bcdd179410d" ON "track_meridians"  ("meridian_id") `);
        await queryRunner.query(`CREATE TYPE "public"."wave_type" AS ENUM('SINE', 'BINAURAL', 'ISOCHRONIC', 'MONAURAL')`);
        await queryRunner.query(`CREATE TYPE "public"."track_status" AS ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "tracks" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT gen_random_uuid(), "slug" character varying(160) NOT NULL, "title" character varying(200) NOT NULL, "description" text NOT NULL, "duration_sec" integer NOT NULL, "frequency_hz" numeric(8,2), "wave_type" "public"."wave_type", "audio_asset_id" uuid NOT NULL, "cover_asset_id" uuid, "status" "public"."track_status" NOT NULL DEFAULT 'DRAFT', "stripe_product_id" character varying(64), "published_at" TIMESTAMP WITH TIME ZONE, "created_by_id" uuid NOT NULL, CONSTRAINT "UQ_696107ffe87d837286180022495" UNIQUE ("slug"), CONSTRAINT "UQ_b4931d3b7997a7fa993234e105a" UNIQUE ("stripe_product_id"), CONSTRAINT "chk_tracks_frequency_positive" CHECK ("frequency_hz" IS NULL OR "frequency_hz" > 0), CONSTRAINT "chk_tracks_duration_positive" CHECK ("duration_sec" > 0), CONSTRAINT "PK_242a37ffc7870380f0e611986e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9c9731a06456ba588cbd57efea" ON "tracks"  ("status") `);
        await queryRunner.query(`CREATE TABLE "program_tracks" ("program_id" uuid NOT NULL, "track_id" uuid NOT NULL, "order_index" integer NOT NULL, CONSTRAINT "uq_program_tracks_order" UNIQUE ("program_id", "order_index") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "chk_program_tracks_order_non_negative" CHECK ("order_index" >= 0), CONSTRAINT "PK_a53a01ce08fba11e94fdeb8f84a" PRIMARY KEY ("program_id", "track_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d08a50bfff7343d9472f8e558" ON "program_tracks"  ("track_id") `);
        await queryRunner.query(`CREATE TYPE "public"."program_status" AS ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "programs" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT gen_random_uuid(), "slug" character varying(160) NOT NULL, "title" character varying(200) NOT NULL, "description" text NOT NULL, "poster_asset_id" uuid, "status" "public"."program_status" NOT NULL DEFAULT 'DRAFT', "stripe_product_id" character varying(64), "published_at" TIMESTAMP WITH TIME ZONE, "created_by_id" uuid NOT NULL, CONSTRAINT "UQ_4180c2bfa0402878a63b70cb4a4" UNIQUE ("slug"), CONSTRAINT "UQ_ba6f88246c087d8ee8832de0f40" UNIQUE ("stripe_product_id"), CONSTRAINT "PK_d43c664bcaafc0e8a06dfd34e05" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4d27843d20a4266a9f9285b84e" ON "programs"  ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."access_grant_source" AS ENUM('ADMIN', 'PROMO')`);
        await queryRunner.query(`CREATE TABLE "access_grants" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "track_id" uuid, "program_id" uuid, "source" "public"."access_grant_source" NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE, "revoked_at" TIMESTAMP WITH TIME ZONE, "note" text, "granted_by_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "chk_access_grants_target_xor" CHECK (num_nonnulls("track_id", "program_id") = 1), CONSTRAINT "PK_451012952c6aa19c9f6e4ddcc19" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_88c268af036108b0891caacce7" ON "access_grants"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "admin_id" uuid NOT NULL, "action" character varying(100) NOT NULL, "entity_type" character varying(100) NOT NULL, "entity_id" character varying(64) NOT NULL, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_entity" ON "audit_logs"  ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE TYPE "public"."billing_interval" AS ENUM('MONTH', 'YEAR')`);
        await queryRunner.query(`CREATE TABLE "prices" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "track_id" uuid, "program_id" uuid, "interval" "public"."billing_interval" NOT NULL, "stripe_price_id" character varying(64) NOT NULL, "amount_minor" integer NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'usd', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_f6fda7cdd493f9803d5173bb3eb" UNIQUE ("stripe_price_id"), CONSTRAINT "chk_prices_amount_positive" CHECK ("amount_minor" > 0), CONSTRAINT "chk_prices_target_xor" CHECK (num_nonnulls("track_id", "program_id") = 1), CONSTRAINT "PK_2e40b9e4e631a53cd514d82ccd2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_prices_active_program_interval" ON "prices"  ("program_id", "interval") WHERE "is_active" = true AND "program_id" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_prices_active_track_interval" ON "prices"  ("track_id", "interval") WHERE "is_active" = true AND "track_id" IS NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_status" AS ENUM('INCOMPLETE', 'INCOMPLETE_EXPIRED', 'TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'UNPAID', 'PAUSED')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "track_id" uuid, "program_id" uuid, "price_id" uuid NOT NULL, "stripe_subscription_id" character varying(64) NOT NULL, "status" "public"."subscription_status" NOT NULL, "current_period_start" TIMESTAMP WITH TIME ZONE, "current_period_end" TIMESTAMP WITH TIME ZONE, "cancel_at_period_end" boolean NOT NULL DEFAULT false, "canceled_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_3a2d09d943f39912a01831a9272" UNIQUE ("stripe_subscription_id"), CONSTRAINT "chk_subscriptions_target_xor" CHECK (num_nonnulls("track_id", "program_id") = 1), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_subscriptions_user_status" ON "subscriptions"  ("user_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_subscriptions_live_user_program" ON "subscriptions"  ("user_id", "program_id") WHERE "program_id" IS NOT NULL AND "status" NOT IN ('CANCELED', 'INCOMPLETE_EXPIRED')`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_subscriptions_live_user_track" ON "subscriptions"  ("user_id", "track_id") WHERE "track_id" IS NOT NULL AND "status" NOT IN ('CANCELED', 'INCOMPLETE_EXPIRED')`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_status" AS ENUM('DRAFT', 'OPEN', 'PAID', 'UNCOLLECTIBLE', 'VOID')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "subscription_id" uuid, "stripe_invoice_id" character varying(64) NOT NULL, "status" "public"."invoice_status" NOT NULL, "amount_paid_minor" integer NOT NULL DEFAULT '0', "amount_refunded_minor" integer NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'usd', "paid_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_0ddf8494c8665a57c670287ccd6" UNIQUE ("stripe_invoice_id"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_26daf5e433d6fb88ee32ce9363" ON "invoices"  ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5152c0aa0f851d9b95972b442e" ON "invoices"  ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c58ff972ce7dffcda79a95762f" ON "invoices"  ("paid_at") `);
        await queryRunner.query(`CREATE TYPE "public"."stripe_event_status" AS ENUM('RECEIVED', 'PROCESSED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "stripe_events" ("id" character varying(64) NOT NULL, "type" character varying(100) NOT NULL, "payload" jsonb NOT NULL, "status" "public"."stripe_event_status" NOT NULL DEFAULT 'RECEIVED', "error" text, "received_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "processed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_d3247bd5fc3f66b6982bbcdd897" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4d617ecf567f4e223f0ea8dbf1" ON "stripe_events"  ("status") `);
        await queryRunner.query(`CREATE TABLE "playback_progress" ("user_id" uuid NOT NULL, "track_id" uuid NOT NULL, "position_sec" integer NOT NULL DEFAULT '0', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7579f21b0d831bdda512dd9ce75" PRIMARY KEY ("user_id", "track_id"))`);
        await queryRunner.query(`CREATE TABLE "playback_sessions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "track_id" uuid NOT NULL, "program_id" uuid, "started_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "last_heartbeat_at" TIMESTAMP WITH TIME ZONE, "listened_sec" integer NOT NULL DEFAULT '0', "counted_as_listen" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_1e16c9dae631d2285c5e6cf47cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_playback_sessions_counted_track" ON "playback_sessions"  ("track_id") WHERE "counted_as_listen" = true`);
        await queryRunner.query(`CREATE INDEX "idx_playback_sessions_user_started" ON "playback_sessions"  ("user_id", "started_at") `);
        await queryRunner.query(`CREATE INDEX "idx_playback_sessions_track_started" ON "playback_sessions"  ("track_id", "started_at") `);
        await queryRunner.query(`CREATE TYPE "public"."auth_provider" AS ENUM('GOOGLE')`);
        await queryRunner.query(`CREATE TABLE "auth_identities" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "provider" "public"."auth_provider" NOT NULL, "provider_user_id" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_aa609852756e5772a11b73f8d83" UNIQUE ("provider", "provider_user_id"), CONSTRAINT "PK_63a29aebcddd09448dbeee4666b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c06a980d83c42611d27a294e55" ON "auth_identities"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "token_hash" character varying(64) NOT NULL, "family_id" uuid NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE, "user_agent" text, "ip" character varying(45), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_a7838d2ba25be1342091b6695f1" UNIQUE ("token_hash"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens"  ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d5e27da0cd39bc3bb2811fc8ba" ON "refresh_tokens"  ("family_id") `);
        await queryRunner.query(`ALTER TABLE "media_assets" ADD CONSTRAINT "FK_9c6b616b5c373c54a0619460eb6" FOREIGN KEY ("uploaded_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_issues" ADD CONSTRAINT "FK_0132948ab072c8b56c4147cd66d" FOREIGN KEY ("track_id") REFERENCES "tracks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_issues" ADD CONSTRAINT "FK_cf45166462d38ec72a4adea48f6" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meridians" ADD CONSTRAINT "FK_3148131d1ea8728e33b67cbcb3c" FOREIGN KEY ("element_id") REFERENCES "elements"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_meridians" ADD CONSTRAINT "FK_4efe7754c1025596d41290d9f7c" FOREIGN KEY ("track_id") REFERENCES "tracks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_meridians" ADD CONSTRAINT "FK_48c337ae000ee39bcdd179410db" FOREIGN KEY ("meridian_id") REFERENCES "meridians"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracks" ADD CONSTRAINT "FK_bb40ed931347794baa092b101d4" FOREIGN KEY ("audio_asset_id") REFERENCES "media_assets"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracks" ADD CONSTRAINT "FK_8c76049dbc695f84b53bb892f34" FOREIGN KEY ("cover_asset_id") REFERENCES "media_assets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracks" ADD CONSTRAINT "FK_0ee013aa9f8a21cde56a2dc723f" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "program_tracks" ADD CONSTRAINT "FK_7947485ef768c474b7e2642aa7c" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "program_tracks" ADD CONSTRAINT "FK_3d08a50bfff7343d9472f8e558a" FOREIGN KEY ("track_id") REFERENCES "tracks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "FK_2eb3cab74fe2b006dcf64c13842" FOREIGN KEY ("poster_asset_id") REFERENCES "media_assets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "FK_b44b72ef368c7a57f4777d81b0f" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "access_grants" ADD CONSTRAINT "FK_88c268af036108b0891caacce7c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "access_grants" ADD CONSTRAINT "FK_9bd503ce215ae97644b35bdf135" FOREIGN KEY ("track_id") REFERENCES "tracks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "access_grants" ADD CONSTRAINT "FK_db47a65fea7c1d451c5022233d6" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "access_grants" ADD CONSTRAINT "FK_c1e764c39141a302c301f78a48e" FOREIGN KEY ("granted_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_b29de603374cbfa7d776d88e5b5" FOREIGN KEY ("admin_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prices" ADD CONSTRAINT "FK_70a82eec6c742ac5085bf452056" FOREIGN KEY ("track_id") REFERENCES "tracks"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prices" ADD CONSTRAINT "FK_4d99a8eb4c59c9e22be95de7618" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_f230c45dda6b32197c797d16d16" FOREIGN KEY ("track_id") REFERENCES "tracks"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_66d13a02994a22147ddeb8c2a6c" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_7f7fe1f6132e48683387c32982c" FOREIGN KEY ("price_id") REFERENCES "prices"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_26daf5e433d6fb88ee32ce93637" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_5152c0aa0f851d9b95972b442e0" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playback_progress" ADD CONSTRAINT "FK_fa081c99ac7a2be4ca27b675d43" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playback_progress" ADD CONSTRAINT "FK_9d62352f7790f84c99084b5c413" FOREIGN KEY ("track_id") REFERENCES "tracks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playback_sessions" ADD CONSTRAINT "FK_0fe3fbaf6603fca327c9deaaea6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playback_sessions" ADD CONSTRAINT "FK_098f7acf0110c0f333b4da0728a" FOREIGN KEY ("track_id") REFERENCES "tracks"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playback_sessions" ADD CONSTRAINT "FK_a98dcd9635c73c2f99abd8b4588" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_identities" ADD CONSTRAINT "FK_c06a980d83c42611d27a294e55c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "auth_identities" DROP CONSTRAINT "FK_c06a980d83c42611d27a294e55c"`);
        await queryRunner.query(`ALTER TABLE "playback_sessions" DROP CONSTRAINT "FK_a98dcd9635c73c2f99abd8b4588"`);
        await queryRunner.query(`ALTER TABLE "playback_sessions" DROP CONSTRAINT "FK_098f7acf0110c0f333b4da0728a"`);
        await queryRunner.query(`ALTER TABLE "playback_sessions" DROP CONSTRAINT "FK_0fe3fbaf6603fca327c9deaaea6"`);
        await queryRunner.query(`ALTER TABLE "playback_progress" DROP CONSTRAINT "FK_9d62352f7790f84c99084b5c413"`);
        await queryRunner.query(`ALTER TABLE "playback_progress" DROP CONSTRAINT "FK_fa081c99ac7a2be4ca27b675d43"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_5152c0aa0f851d9b95972b442e0"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_26daf5e433d6fb88ee32ce93637"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_7f7fe1f6132e48683387c32982c"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_66d13a02994a22147ddeb8c2a6c"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_f230c45dda6b32197c797d16d16"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1"`);
        await queryRunner.query(`ALTER TABLE "prices" DROP CONSTRAINT "FK_4d99a8eb4c59c9e22be95de7618"`);
        await queryRunner.query(`ALTER TABLE "prices" DROP CONSTRAINT "FK_70a82eec6c742ac5085bf452056"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_b29de603374cbfa7d776d88e5b5"`);
        await queryRunner.query(`ALTER TABLE "access_grants" DROP CONSTRAINT "FK_c1e764c39141a302c301f78a48e"`);
        await queryRunner.query(`ALTER TABLE "access_grants" DROP CONSTRAINT "FK_db47a65fea7c1d451c5022233d6"`);
        await queryRunner.query(`ALTER TABLE "access_grants" DROP CONSTRAINT "FK_9bd503ce215ae97644b35bdf135"`);
        await queryRunner.query(`ALTER TABLE "access_grants" DROP CONSTRAINT "FK_88c268af036108b0891caacce7c"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "FK_b44b72ef368c7a57f4777d81b0f"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "FK_2eb3cab74fe2b006dcf64c13842"`);
        await queryRunner.query(`ALTER TABLE "program_tracks" DROP CONSTRAINT "FK_3d08a50bfff7343d9472f8e558a"`);
        await queryRunner.query(`ALTER TABLE "program_tracks" DROP CONSTRAINT "FK_7947485ef768c474b7e2642aa7c"`);
        await queryRunner.query(`ALTER TABLE "tracks" DROP CONSTRAINT "FK_0ee013aa9f8a21cde56a2dc723f"`);
        await queryRunner.query(`ALTER TABLE "tracks" DROP CONSTRAINT "FK_8c76049dbc695f84b53bb892f34"`);
        await queryRunner.query(`ALTER TABLE "tracks" DROP CONSTRAINT "FK_bb40ed931347794baa092b101d4"`);
        await queryRunner.query(`ALTER TABLE "track_meridians" DROP CONSTRAINT "FK_48c337ae000ee39bcdd179410db"`);
        await queryRunner.query(`ALTER TABLE "track_meridians" DROP CONSTRAINT "FK_4efe7754c1025596d41290d9f7c"`);
        await queryRunner.query(`ALTER TABLE "meridians" DROP CONSTRAINT "FK_3148131d1ea8728e33b67cbcb3c"`);
        await queryRunner.query(`ALTER TABLE "track_issues" DROP CONSTRAINT "FK_cf45166462d38ec72a4adea48f6"`);
        await queryRunner.query(`ALTER TABLE "track_issues" DROP CONSTRAINT "FK_0132948ab072c8b56c4147cd66d"`);
        await queryRunner.query(`ALTER TABLE "media_assets" DROP CONSTRAINT "FK_9c6b616b5c373c54a0619460eb6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5e27da0cd39bc3bb2811fc8ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddc983c5f7bcf132fd8732c3f"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c06a980d83c42611d27a294e55"`);
        await queryRunner.query(`DROP TABLE "auth_identities"`);
        await queryRunner.query(`DROP TYPE "public"."auth_provider"`);
        await queryRunner.query(`DROP INDEX "public"."idx_playback_sessions_track_started"`);
        await queryRunner.query(`DROP INDEX "public"."idx_playback_sessions_user_started"`);
        await queryRunner.query(`DROP INDEX "public"."idx_playback_sessions_counted_track"`);
        await queryRunner.query(`DROP TABLE "playback_sessions"`);
        await queryRunner.query(`DROP TABLE "playback_progress"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d617ecf567f4e223f0ea8dbf1"`);
        await queryRunner.query(`DROP TABLE "stripe_events"`);
        await queryRunner.query(`DROP TYPE "public"."stripe_event_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c58ff972ce7dffcda79a95762f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5152c0aa0f851d9b95972b442e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26daf5e433d6fb88ee32ce9363"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_status"`);
        await queryRunner.query(`DROP INDEX "public"."uq_subscriptions_live_user_track"`);
        await queryRunner.query(`DROP INDEX "public"."uq_subscriptions_live_user_program"`);
        await queryRunner.query(`DROP INDEX "public"."idx_subscriptions_user_status"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_status"`);
        await queryRunner.query(`DROP INDEX "public"."uq_prices_active_track_interval"`);
        await queryRunner.query(`DROP INDEX "public"."uq_prices_active_program_interval"`);
        await queryRunner.query(`DROP TABLE "prices"`);
        await queryRunner.query(`DROP TYPE "public"."billing_interval"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_entity"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88c268af036108b0891caacce7"`);
        await queryRunner.query(`DROP TABLE "access_grants"`);
        await queryRunner.query(`DROP TYPE "public"."access_grant_source"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d27843d20a4266a9f9285b84e"`);
        await queryRunner.query(`DROP TABLE "programs"`);
        await queryRunner.query(`DROP TYPE "public"."program_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d08a50bfff7343d9472f8e558"`);
        await queryRunner.query(`DROP TABLE "program_tracks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c9731a06456ba588cbd57efea"`);
        await queryRunner.query(`DROP TABLE "tracks"`);
        await queryRunner.query(`DROP TYPE "public"."track_status"`);
        await queryRunner.query(`DROP TYPE "public"."wave_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48c337ae000ee39bcdd179410d"`);
        await queryRunner.query(`DROP TABLE "track_meridians"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3148131d1ea8728e33b67cbcb3"`);
        await queryRunner.query(`DROP TABLE "meridians"`);
        await queryRunner.query(`DROP TYPE "public"."polarity"`);
        await queryRunner.query(`DROP TABLE "elements"`);
        await queryRunner.query(`DROP TYPE "public"."wu_xing_element"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf45166462d38ec72a4adea48f"`);
        await queryRunner.query(`DROP TABLE "track_issues"`);
        await queryRunner.query(`DROP TABLE "issues"`);
        await queryRunner.query(`DROP TABLE "media_assets"`);
        await queryRunner.query(`DROP TYPE "public"."media_status"`);
        await queryRunner.query(`DROP TYPE "public"."media_kind"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."user_role"`);
    }

}
